---
- name: install rbenv and ruby-build
  homebrew: name={{ item }} state=latest
  with_items:
    - rbenv
    - ruby-build

- name: place bashrc configuration file
  become: yes
  copy:
    src: bashrc.rbenv.sh
    dest: /etc/bashrc.rbenv.sh
    owner: root
    group: wheel
    mode: 0644

- name: add configuration file to bashrc
  become: yes
  lineinfile: >
    dest=/etc/bashrc
    regexp="bashrc.rbenv.sh"
    line="if [ -f /etc/bashrc.rbenv.sh ]; then . /etc/bashrc.rbenv.sh; fi"
    state=present
    create=true

- name: install gems for system
  become: yes
  shell: gem install {{ item }}
  with_items: default_system_gems

- name: install rbenv versions
  shell: "(rbenv versions --bare | grep ^{{ item }}$) || rbenv install {{ item }}"
  with_items: rbenv_versions

- name: install gems for each rbenv versions
  shell: "RBENV_VERSION={{ item.ruby_version }} gem install {{ item.gems }}"
  with_items: rbenv_gems_for_versions

- name: set default rbenv versions
  shell: rbenv global {{ default_rbenv_version }}